version: "3.2"

services:

  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - 27017:27017
    volumes:
      - ~/.docker-conf/mongodb/data/:/data/db
    networks:
      - servico-votacao

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - servico-votacao

  api-votcao:
    image: willianksantos/api-votacao
    container_name: 'api-votacao'
    ports:
      - 8080:8080
    depends_on:
      - 'mongodb'
      - 'rabbitmq'
    networks:
      - servico-votacao

networks:
  servico-votacao:
    driver: bridge